# Generated by Django 4.0.6 on 2022-07-18 13:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=127)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Non-binary')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('workout_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('set_number', models.PositiveSmallIntegerField()),
                ('weight', models.PositiveSmallIntegerField()),
                ('reps', models.PositiveSmallIntegerField()),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_tracker.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutTemplateExercise',
            fields=[
                ('workout_exercises_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_tracker.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutTemplate',
            fields=[
                ('workout_template_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('workout_exercises_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_tracker.workouttemplateexercise')),
            ],
        ),
        migrations.CreateModel(
            name='UserWorkoutTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_tracker.user')),
                ('workout_template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_tracker.workouttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_tracker.user')),
                ('workout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_tracker.workout')),
                ('workout_template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_tracker.workouttemplate')),
            ],
            options={
                'unique_together': {('user_id', 'workout_template_id', 'workout_id')},
            },
        ),
    ]
