# Generated by Django 4.0.6 on 2022-07-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_tracker', '0002_alter_weightlog_time_alter_workoutlog_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightlog',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='workout',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
