# Generated by Django 4.0.6 on 2022-07-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_tracker', '0002_alter_exercisemusclesworked_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='exercisemusclesworked',
            unique_together={('exercise_id', 'muscle')},
        ),
    ]
